create table if not exists public.stock (
  id bigint generated by default as identity primary key,
  core text not null unique,
  description text not null,
  location text not null,
  quantity integer not null default 0,
  minimum_stock integer not null default 0,
  last_updated text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.history (
  id bigint generated by default as identity primary key,
  type text not null,
  core text not null,
  quantity integer not null default 0,
  reason text,
  user text,
  destination text,
  department text,
  date text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.shipments (
  id bigint generated by default as identity primary key,
  week_number integer not null,
  core text not null,
  weekly_requirement integer not null default 0,
  quantity_shipped integer not null default 0,
  remaining_to_ship integer not null default 0,
  destination text not null,
  status text not null,
  created_at timestamp with time zone default now(),
  unique (core, week_number, destination)
);

create table if not exists public.rejects (
  id bigint generated by default as identity primary key,
  core text not null,
  quantity integer not null default 0,
  department text not null,
  reason text not null,
  operator text not null,
  date text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.adjustments (
  id bigint generated by default as identity primary key,
  core text not null,
  adjustment_type text not null,
  quantity integer not null default 0,
  reason text not null,
  operator text not null,
  date text not null,
  created_at timestamp with time zone default now()
);
